import pandas as pd
import math
import os
import numpy as np
from config import GROUPED_FOLDER, FILTERED_FOLDER, MIN_RR



def compute_score(df, threshold):
    total_trades = len(df)
    numeric_rr = pd.to_numeric(df["reward_risk"], errors="coerce")

    # Trades at or above threshold: +T each
    wins = numeric_rr >= threshold
    win_score = int(wins.sum()) * threshold

    # Positive trades below threshold: -1 each
    below_threshold = (numeric_rr > 0) & (numeric_rr < threshold)
    below_score = -int(below_threshold.sum())

    # Normal SL: -1 each
    sl_trades = df["reward_risk"] == "SL"
    sl_score = -int(sl_trades.sum())



    penalty = math.floor(total_trades / 10)

    score = win_score + below_score + sl_score - penalty
    return score


def main():
    """
    Step 3 – Score and Filter.
    For each reward/risk threshold T, load each grouped CSV file,
    compute score, keep only files with score > 0.
    """
    # Ensure grouped folder exists
    if not os.path.exists(GROUPED_FOLDER):
        print(f"ERROR: {GROUPED_FOLDER} not found. Run step2_grouped.py first.")
        return

    # Determine thresholds from trades.csv (should be generated by step1)
    # If trades.csv not available, fallback to MIN_RR and a default range.
    # We'll compute thresholds similarly to step1_extract.py.
    if os.path.exists("trades.csv"):
        df_trades = pd.read_csv("trades.csv")
        numeric_rr = pd.to_numeric(df_trades["reward_risk"], errors="coerce")
        positive_rr = numeric_rr[numeric_rr >= MIN_RR]
        thresholds = sorted(positive_rr.apply(np.floor).astype(int).unique().tolist())
    else:
        thresholds = [int(MIN_RR)]  # default

    print(f"Thresholds: {thresholds}")

    # Ensure filtered folder exists
    os.makedirs(FILTERED_FOLDER, exist_ok=True)

    # Collect surviving files per threshold
    surviving_files = {}
    for T in thresholds:
        surviving = []
        # List all grouped CSV files
        for filename in os.listdir(GROUPED_FOLDER):
            if not filename.endswith(".csv"):
                continue
            filepath = os.path.join(GROUPED_FOLDER, filename)
            df = pd.read_csv(filepath)
            score = compute_score(df, T)
            if score > 0:
                surviving.append(filename)
                # Copy file to filtered subfolder (optional)
                subfolder = os.path.join(FILTERED_FOLDER, str(T))
                os.makedirs(subfolder, exist_ok=True)
                df.to_csv(os.path.join(subfolder, filename), index=False)
        surviving_files[T] = surviving
        print(f"Threshold {T}: {len(surviving)} surviving files")

    # Write manifest (optional)
    manifest_path = os.path.join(FILTERED_FOLDER, "surviving_files.csv")
    with open(manifest_path, "w") as f:
        f.write("threshold,filename\n")
        for T, files in surviving_files.items():
            for filename in files:
                f.write(f"{T},{filename}\n")
    print(f"Manifest saved to {manifest_path}")


if __name__ == "__main__":
    main()